title: Grav
author:
  name: Joe Bloggs
  email: 'joe@test.com'
blog:
  route: ''
metadata:
    description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
taxonomies: [category,tag,month]

